### ISSUE TITLE
Setup Heroku services

### ISSUE THREAD

**Issue by josepjaume** [AjuntamentDeTerrassa/decidim-terrassa#13]
- [x] Sendgrid
- [x] Logentries
- [x] New Relic (free)
- [x] Memcached cloud
- [x] Sentry

**Comment by mrcasals** [comment]
We'll use LogDNA instead of Logentries /cc @oriolgual

**Comment by mrcasals** [comment]
Closed by #22

**Comment by mrcasals** [comment]
turns out the cool one was LogEntries, so we're actually using this one instead of LogDNA.
