### ISSUE TITLE
Setup deployment and Review Apps

### ISSUE THREAD

**Issue by josepjaume** [AjuntamentDeTerrassa/decidim-terrassa#2]
We should setup deployment on heroku and activate review apps for this repo.

**Comment by mrcasals** [comment]
I've made a generator for review apps, see https://github.com/AjuntamentdeBarcelona/decidim/pull/1123. I will run it here once it's merged in the main repo.

**Comment by josepjaume** [comment]
Nice!

**Comment by mrcasals** [comment]
Deployment set up! http://decidim-terrassa.herokuapp.com

Review apps are not set up yet.
