### ISSUE TITLE
Setup continuous deployment

### ISSUE THREAD

**Issue by josepjaume** [AjuntamentDeTerrassa/decidim-terrassa#4]
Setup Travis CI for this app. It should at least:

* Boot the app and check the first page includes `Terrassa`

**Comment by mrcasals** [comment]
Should we wait for TravisCI to pass before automatically deploying to Heroku?

**Comment by oriolgual** [comment]
Yup

**Comment by josepjaume** [comment]
I usually don't leave this check because it introduces latency on the deploy (having to wait for potentially a long queue) and uncertainty (will it passss??). 

The best way to set this up IMO is setting up travis to it only builds the PRs (merging against master) so you have a reasonable degree of confidence the code in master also passes, without having to wait for the CI every time.

**Comment by mrcasals** [comment]
+1 to what @josepjaume says, so by now I will disable this option.

**Comment by mrcasals** [comment]
Pending: add the tests.
