### ISSUE TITLE
Configure the right domain and SSL certificate

### ISSUE THREAD

**Issue by josepjaume** [AjuntamentDeTerrassa/decidim-terrassa#9]
Configure the app so it points to `decidim.terrassa.cat` and add the appropiate SSL certificate (in case we don't have an official one, let's use letsencrypt).

**Comment by oriolgual** [comment]
And force the app to use only SSL at production.

**Comment by josepjaume** [comment]
@mrcasals you can now use Heroku SSL certs: https://blog.heroku.com/announcing-automated-certificate-management

**Comment by mrcasals** [comment]
@josepjaume I think we need the app to point to the correct domain first:

> You will need to ensure that your application’s custom domains are pointed to the correct DNS targets as specified in `heroku domains`.

**Comment by oriolgual** [comment]
This has been done thanks to the new Heroku SSL feature.
